name: nsg_template_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^5.0.0-beta.52
  nsg_data:
    path: 
      ../nsg_data
  nsg_controls:
    path: 
      ../nsg_controls

  intl: ^0.18.0
  flutter_svg: ^2.0.1
  simple_shadow: ^0.3.0
  flutter_slidable: ^3.0.0
  slidable_button: ^1.3.1
  flutter_fadein: ^2.0.0
  jiffy: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/
    - lib/assets/images/
